import LeanFormal.IUT.Project

/-!
  The declarations below are the trust-boundary sample for the production
  project.  The output is recorded by the accompanying audit log; in
  particular, `theorem311_produces_stepXI_contract` must expose `sorryAx`.
-/

open LeanFormal.IUT

#print axioms LeanFormal.IUT.card_Fl
#print axioms LeanFormal.IUT.natRadical_mul_three_of_pairwise_coprime
#print axioms LeanFormal.IUT.natRadical_dvd_radical_of_dvd
#print axioms LeanFormal.IUT.PrimitiveAdditiveTriple.radical_product_eq
#print axioms LeanFormal.IUT.primeStrip_finite
#print axioms LeanFormal.IUT.primeStrip_subset_of_interval
#print axioms LeanFormal.IUT.ellipticModelWithJ
#print axioms LeanFormal.IUT.ellipticModelWithJ_j
#print axioms LeanFormal.IUT.PuncturedEllipticCurve.jInvariant_spec
#print axioms LeanFormal.IUT.PuncturedEllipticCurve.projectivePointClassMap_mk
#print axioms LeanFormal.IUT.PuncturedEllipticCurve.projectiveNonsingularLift_map
#print axioms LeanFormal.IUT.PuncturedEllipticCurve.projectivePointMap_point
#print axioms LeanFormal.IUT.PuncturedEllipticCurve.map_curve
#print axioms LeanFormal.IUT.PuncturedEllipticCurve.map_puncture
#print axioms LeanFormal.IUT.PuncturedEllipticCurve.baseChange_curve
#print axioms LeanFormal.IUT.hasSplitMultiplicativeReductionOnMinimalModel_smul_iff
#print axioms LeanFormal.IUT.PuncturedEllipticCurve.hasSplitMultiplicativeReductionAt_imp_multiplicative
#print axioms LeanFormal.IUT.PuncturedEllipticCurve.galoisActionOnPoint_mul
#print axioms LeanFormal.IUT.PuncturedEllipticCurve.galoisActionOnPoint_stabilizer_isOpen
#print axioms LeanFormal.IUT.PuncturedEllipticCurve.galoisLTorsionMatrixRepresentation_acts
#print axioms LeanFormal.IUT.PuncturedEllipticCurve.galoisLTorsionMatrixRepresentation_continuous
#print axioms LeanFormal.IUT.PuncturedEllipticCurve.galoisLTorsionKernelField_fixingSubgroup
#print axioms LeanFormal.IUT.det_diagonal_mul
#print axioms LeanFormal.IUT.det_diagonal_tensor
#print axioms LeanFormal.IUT.log_prod_positive
#print axioms LeanFormal.IUT.log_const_mul_sum
#print axioms LeanFormal.IUT.card_LabCusp
#print axioms LeanFormal.IUT.log_realThetaValue
#print axioms LeanFormal.IUT.FiniteThetaPacket.scale_pos
#print axioms LeanFormal.IUT.FiniteThetaPacket.scale_neg
#print axioms LeanFormal.IUT.FiniteThetaPacket.log_scale
#print axioms LeanFormal.IUT.FiniteThetaPacket.logVolume_neg_invariant
#print axioms LeanFormal.IUT.thetaToElliptic_mk
#print axioms LeanFormal.IUT.modLThetaProjection_surjective
#print axioms LeanFormal.IUT.modLThetaToElliptic_surjective
#print axioms LeanFormal.IUT.thetaCenter_le_center
#print axioms LeanFormal.IUT.gaussianSquareSum_formula
#print axioms LeanFormal.IUT.normalizedGaussianDegree_eq_factor
#print axioms LeanFormal.IUT.primeStrip_finite
#print axioms LeanFormal.IUT.primeStrip_subset_of_interval
#print axioms LeanFormal.IUT.PrimeGeFive.odd
#print axioms LeanFormal.IUT.ThetaFieldTower.sqrtNegOne_spec
#print axioms LeanFormal.IUT.ThetaFieldTower.degreePrimeToL_spec
#print axioms LeanFormal.IUT.DPrimeStrip.geometric_carrier
#print axioms LeanFormal.IUT.DPrimeStripEquiv.symm
#print axioms LeanFormal.IUT.DPrimeStripEquiv.trans
#print axioms LeanFormal.IUT.FPrimeStrip.totalDegree_mul
#print axioms LeanFormal.IUT.FPrimeStrip.totalDegree_one
#print axioms LeanFormal.IUT.FPrimeStrip.action_mul
#print axioms LeanFormal.IUT.FPrimeStrip.action_one
#print axioms LeanFormal.IUT.FPrimeStripEquiv.symm
#print axioms LeanFormal.IUT.FPrimeStripEquiv.trans
#print axioms LeanFormal.IUT.HodgeTheaterLink.symm
#print axioms LeanFormal.IUT.HodgeTheaterLink.trans
#print axioms LeanFormal.IUT.ThreeTheaterSystem.sourceToTarget_q
#print axioms LeanFormal.IUT.ThreeTheaterSystem.sourceToTarget_scale
#print axioms LeanFormal.IUT.localDPrimeStrip
#print axioms LeanFormal.IUT.finiteLocalDPrimeStrip
#print axioms LeanFormal.IUT.localGaloisUnitsAction
#print axioms LeanFormal.IUT.localQParameter_ne_one
#print axioms LeanFormal.IUT.localUnitNormDegreeFor_apply_mul
#print axioms LeanFormal.IUT.localFPrimeStrip_degree_mul
#print axioms LeanFormal.IUT.KummerPolynomialData.root_pow_eq
#print axioms LeanFormal.IUT.KummerPolynomialData.root_ne_zero
#print axioms LeanFormal.IUT.localKummerPolynomialFor_root_pow_eq
#print axioms LeanFormal.IUT.AdjoinRootEmbedding.lift_root
#print axioms LeanFormal.IUT.AdjoinRootEmbedding.lift_of
#print axioms LeanFormal.IUT.AdjoinRootEmbedding.root_ne_zero
#print axioms LeanFormal.IUT.localKummerRootRealizationFor_root_ne_zero
#print axioms LeanFormal.IUT.CompatibleRootSystem.quotient_pow_den
#print axioms LeanFormal.IUT.NatRootSystem.pow_self
#print axioms LeanFormal.IUT.NatRootSystem.pow
#print axioms LeanFormal.IUT.AlgebraicClosureRootSystem.exists_pow_root
#print axioms LeanFormal.IUT.AlgebraicClosureRootSystem.chainRoot_spec
#print axioms LeanFormal.IUT.AlgebraicClosureRootSystem.chainRoot_telescope
#print axioms LeanFormal.IUT.AlgebraicClosureRootSystem.rootSystemOfAlgClosed
#print axioms LeanFormal.IUT.KummerClass.kummerClass_one
#print axioms LeanFormal.IUT.KummerClass.kummerClass_mul
#print axioms LeanFormal.IUT.KummerClass.kummerClass_diff
#print axioms LeanFormal.IUT.KummerRootRatioData.ratioUnit_zero
#print axioms LeanFormal.IUT.KummerRootRatioData.ratioUnit_add
#print axioms LeanFormal.IUT.VerticalLogKummerCorrespondence.transport_zero
#print axioms LeanFormal.IUT.VerticalLogKummerCorrespondence.kummer_le_transport
#print axioms LeanFormal.IUT.VerticalLogKummerCorrespondence.base_le_hull
#print axioms LeanFormal.IUT.PrimeStripDegree.localDegree_mul
#print axioms LeanFormal.IUT.PrimeStripDegree.totalDegree_mul
#print axioms LeanFormal.IUT.PrimeStripDegree.totalDegree_one
#print axioms LeanFormal.IUT.unitNormLogDegree_apply_mul
#print axioms LeanFormal.IUT.unitNormLogDegree_apply_one
#print axioms LeanFormal.IUT.norm_pos_unit
#print axioms LeanFormal.IUT.padicValNat_mul_of_nonzero
#print axioms LeanFormal.IUT.padicValNat_pow_nat
#print axioms LeanFormal.IUT.prime_dvd_iff_padicValNat_ne_zero
#print axioms LeanFormal.IUT.prime_pow_dvd_iff_padicValNat_le
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.mk_underlyingPrime
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.residueCharacteristic_prime
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.residueCharacteristic_pos
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.comap_maximalIdeal
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.comap_comap
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.comap_surjective
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.valuation_algebraMap
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.uniformContinuous_algebraMap
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.continuous_completionMap
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.completionMap_injective
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.completionMap_coe
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.valuation_completionMap
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.completionMap_mem_adicCompletionIntegers
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.completionIntegersMap_injective
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.completionMap_comp_algebraMap
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.ramificationIdx_ne_zero
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.isLocalHom_completionIntegersMap
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.residueMap_residue
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.residueMap_injective
#print axioms LeanFormal.IUT.isIntegral_map_of_commutes
#print axioms LeanFormal.IUT.splitReductionPolynomial_map
#print axioms LeanFormal.IUT.integralModel_map_eq_of_commutes
#print axioms LeanFormal.IUT.residue_comp_commutes
#print axioms LeanFormal.IUT.splitReductionPolynomial_map_residue
#print axioms LeanFormal.IUT.isMinimal_of_isIntegral_valuation_Δ_eq_one
#print axioms LeanFormal.IUT.isMinimal_of_isIntegral_valuation_c₄_eq_one
#print axioms LeanFormal.IUT.hasGoodReduction_map_of_commutes
#print axioms LeanFormal.IUT.hasMultiplicativeReduction_map_of_commutes
#print axioms LeanFormal.IUT.reduction_map_eq_of_commutes
#print axioms LeanFormal.IUT.hasSplitMultiplicativeReduction_map_of_commutes
#print axioms LeanFormal.IUT.hasGoodReductionOnMinimalModel_map_of_commutes
#print axioms LeanFormal.IUT.hasMultiplicativeReductionOnMinimalModel_map_of_commutes
#print axioms LeanFormal.IUT.hasSplitMultiplicativeReductionOnMinimalModel_map_of_commutes
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.hasGoodReductionOnMinimalModel_completionMap
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.hasGoodReductionOnMinimalModel_baseChange
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.hasMultiplicativeReductionOnMinimalModel_completionMap
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.hasMultiplicativeReductionOnMinimalModel_baseChange
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.hasSplitMultiplicativeReductionOnMinimalModel_completionMap
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.hasSplitMultiplicativeReductionOnMinimalModel_baseChange
#print axioms LeanFormal.IUT.PuncturedEllipticCurve.baseChange_curve_adicCompletion
#print axioms LeanFormal.IUT.PuncturedEllipticCurve.hasGoodReductionAt_baseChange
#print axioms LeanFormal.IUT.PuncturedEllipticCurve.hasMultiplicativeReductionAt_baseChange
#print axioms LeanFormal.IUT.PuncturedEllipticCurve.hasSplitMultiplicativeReductionAt_baseChange
#print axioms LeanFormal.IUT.PuncturedEllipticCurve.hasStableReductionAt_baseChange
#print axioms LeanFormal.IUT.PuncturedEllipticCurve.hasStableReductionEverywhere_baseChange
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.finitePlaceQCandidate_nonempty
#print axioms LeanFormal.IUT.NumberFieldFinitePlace.FinitePlaceQCandidate.order_pos
#print axioms LeanFormal.IUT.NumberFieldPlace.comap_comap
#print axioms LeanFormal.IUT.NumberFieldPlace.RestrictionSection.lift_injective
#print axioms LeanFormal.IUT.NumberFieldPlace.RestrictionSection.selectedEquiv_symm_apply
#print axioms LeanFormal.IUT.WeightedValues.average_le_of_pointwise
#print axioms LeanFormal.IUT.packetDet_eq_prod
#print axioms LeanFormal.IUT.packetLogVolume_eq_log_det
#print axioms LeanFormal.IUT.packetDet_tensor
#print axioms LeanFormal.IUT.packetLogVolume_tensor
#print axioms LeanFormal.IUT.packetDet_rescale
#print axioms LeanFormal.IUT.packetLogVolume_rescale
#print axioms LeanFormal.IUT.FiniteThetaPacket.toPositivePacket_det_eq_prod
#print axioms LeanFormal.IUT.FiniteThetaPacket.toPositivePacket_logVolume_eq_log_det
#print axioms LeanFormal.IUT.FiniteThetaPacket.toPositivePacket_neg_invariant
#print axioms LeanFormal.IUT.FiniteThetaPacket.toPositivePacket_det_rescale
#print axioms LeanFormal.IUT.FiniteThetaPacket.toPositivePacket_logVolume_rescale
#print axioms LeanFormal.IUT.FiniteHull.average_le
#print axioms LeanFormal.IUT.StepXIFiniteCertificate.q_le_theta
#print axioms LeanFormal.IUT.cor312_of_finite_certificate
#print axioms LeanFormal.IUT.q_positive_of_finite_certificate
#print axioms LeanFormal.IUT.QuotientCompatibleMap.lift_mk
#print axioms LeanFormal.IUT.ThreeLayerQuotientChain.transport_mk
#print axioms LeanFormal.IUT.OrbitCompatibleMap.respects_orbit
#print axioms LeanFormal.IUT.OrbitCompatibleMap.quotientMap_mk
#print axioms LeanFormal.IUT.ThreeLayerOrbitChain.transport_mk
#print axioms LeanFormal.IUT.UpperSemiCorrespondence.singleton
#print axioms LeanFormal.IUT.UpperSemiCorrespondence.comp
#print axioms LeanFormal.IUT.UpperSemiCorrespondence.upper_of_comp
#print axioms LeanFormal.IUT.cor312_of_constructed_stepXI
#print axioms LeanFormal.IUT.q_positive_of_constructed_stepXI
#print axioms LeanFormal.IUT.theorem311_produces_stepXI_contract
#print axioms LeanFormal.IUT.Cor312RouteCertificate.conclusion
#print axioms LeanFormal.IUT.radical_dvd_self
#print axioms LeanFormal.IUT.IsABCTriple.pairwise_coprime
#print axioms LeanFormal.IUT.IsABCTriple.radical_product_eq
#print axioms LeanFormal.IUT.RealTransport.log_map
#print axioms LeanFormal.IUT.FiniteTransitiveAction.card_mul_stabilizer
#print axioms LeanFormal.IUT.FiniteTransitiveAction.card_stabilizer_dvd_group
