import Iut.Foundations.SourceGluedAnabelioid
import Iut.Foundations.SourceGluedGalois
import Iut.Foundations.SourceAnabelioidSlice
import Iut.Foundations.SourceSemiGraphResidualSeparation
import Iut.Foundations.SourceNestedNormalQuotientSystem
import Iut.Foundations.SourceTemperoidQuotient
import Iut.Foundations.SourceTemperedDeckProjectionSurjectivity
import Iut.Foundations.SourceTemperoidOrbitDecomposition
import Iut.Foundations.SourceTemperoidRestrictionComponentFamily
import Iut.Foundations.SourceConnectedFiniteEtaleConverse

/-!
  Trust-boundary audit for the imported semi-graph-of-anabelioids foundation.
  These declarations cover the pointwise finite-limit and supported finite-
  colimit constructions repaired for Lean/Mathlib 4.32.2, their preservation
  by vertex evaluation, and the resulting pre-Galois structure.
-/

#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.limitCone
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.limitConeIsLimit
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.evaluationMapLimitConeIsLimit
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.evaluationPreservesFiniteLimits
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.colimitCocone
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.colimitCoconeIsColimit
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.evaluationMapColimitCoconeIsColimit
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.evaluationPreservesFiniteCoproducts
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.evaluationPreservesFiniteGroupQuotientSmall
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.preGaloisCategory
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.complementFiberIsEmptyOfEpi
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.rootFiberFunctor
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.galoisCategory

#print axioms Iut.sourceInducedIdentityFiber_first_mem
#print axioms Iut.sourceInducedIdentityFiberToOriginal_original
#print axioms Iut.sourceInducedSliceFiberEvaluation_injective
#print axioms Iut.sourceContinuousAction_comp_apply
#print axioms Iut.sourceOpenCosetSliceEquivalence
#print axioms Iut.sourceSliceProductAdjDependentSection
#print axioms Iut.sourceInductionRestrictionAdjunction
#print axioms Iut.sourceOpenSubgroupFiniteEtaleFactorization

/-! Countable-base and finite-separator kernels ported from
`promachina/iut-lean@36ef280d`. -/

#print axioms Iut.SourceFiniteSheetSemiGraphCover.projection_vertexFiber_finite
#print axioms Iut.SourceFiniteSheetSemiGraphCover.projection_edgeFiber_finite
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.GaloisLevel.vertex_countable
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.GaloisLevel.edge_countable
#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.deckGroup_countable
#print axioms Iut.SourceSemiGraphResidualSeparation.separationCover_vertex_countable
#print axioms Iut.SourceSemiGraphResidualSeparation.separationCover_edge_countable
#print axioms Iut.SourceSemiGraphResidualSeparation.separationTreeProjection_liftUniversalVertex

/-! Generic quotient and compatible-family inverse-limit kernel extracted from
`promachina/iut-lean@581e2b89`. -/

#print axioms Iut.SourceNestedNormalQuotientSystem.transition_mk
#print axioms Iut.SourceNestedNormalQuotientSystem.transition_surjective
#print axioms Iut.SourceNestedNormalQuotientSystem.transition_continuous
#print axioms Iut.SourceNestedNormalQuotientSystem.canonicalMap_continuous
#print axioms Iut.SourceNestedNormalQuotientSystem.canonicalMap_projection
#print axioms Iut.SourceNestedNormalQuotientSystem.canonicalMap_injective

/-! Connected finite coverings, kernel orbits, countable temperoids, and the
kernel-orbit/restriction adjunction ported from `promachina/iut-lean`. -/

#print axioms Iut.SourceConnectedCoveringCategory.categoryIsConnected
#print axioms Iut.SourceConnectedCoveringCategory.connected_iff_pretransitive
#print axioms Iut.EtaleFundamentalGroup.coverActionEquivalence

#print axioms Iut.SourceKernelOrbit.kernel_fixes
#print axioms Iut.SourceKernelOrbit.smul_mk
#print axioms Iut.SourceKernelOrbit.targetContinuous

#print axioms Iut.SourceConnectedTemperoid.connected_iff_nonempty_pretransitive
#print axioms Iut.SourceConnectedTemperoid.hom_surjective
#print axioms Iut.SourceConnectedTemperoid.categoryIsConnected
#print axioms Iut.SourceTemperoidAction.finiteInclusionFullyFaithful

#print axioms Iut.SourceTemperoidKernelQuotient.fiberTargetContinuous
#print axioms Iut.SourceTemperoidKernelQuotient.homEquiv
#print axioms Iut.SourceTemperoidKernelQuotient.adjunction
#print axioms Iut.SourceTemperoidKernelQuotient.restrictionFull
#print axioms Iut.SourceTemperoidKernelQuotient.connectedRestrictionFullyFaithful
#print axioms Iut.SourceTemperoidKernelQuotient.connectedAdjunction

#print axioms Iut.CategoryTheory.Functor.eval_section_surjective_of_bounded_lifts
#print axioms Iut.SourceCombinatorialUniversalCover.UniversalVertex.mapHom_bounded_surjective
#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.refinementIncidenceMap_fiber_finite
#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.refinementTreeMap_bounded_surjective
#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.refinementTreeMap_boundedFiber_finite
#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.deckTransition_surjective
#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.deckTransition_boundedFiber_finite
#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.deckTypeDiagram_eval_section_surjective
#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.rawDeckProjection_surjective
#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.literalTemperedPresentation_projection_surjective

#print axioms Iut.SourceTemperedGroupPresentation.projectionKernel_fixes_connectedAction
#print axioms Iut.SourceTemperedGroupPresentation.connectedActionLevelFactorization
#print axioms Iut.SourceCountableGroupDiagram.connectedActionLevelFactorization
#print axioms Iut.sourceTemperoidOrbitDecompositionIso
#print axioms Iut.SourceTemperedGroupPresentation.orbitLevelFactorization
#print axioms Iut.sourceTemperoidComponentFamilyActionIso
#print axioms Iut.sourceRestrictedComponentFamilyActionIso
#print axioms Iut.SourceFiniteEtaleFunctorFactorization.connectedObjectProfiniteInclusion_isOpenEmbedding
#print axioms Iut.SourceFiniteEtaleFunctorFactorization.connectedFiniteEtaleHom
#print axioms Iut.SourceFiniteEtaleFunctorFactorization.connectedFiniteEtaleHom_fundamentalGroupHom_eq
