import Iut.Foundations.SourceGluedAnabelioid
import Iut.Foundations.SourceGluedGalois
import Iut.Foundations.SourceAnabelioidSlice
import Iut.Foundations.SourceSemiGraphResidualSeparation
import Iut.Foundations.SourceNestedNormalQuotientSystem
import Iut.Foundations.SourceTemperoidQuotient
import Iut.Foundations.SourceTemperedDeckProjectionSurjectivity
import Iut.Foundations.SourceTemperoidOrbitDecomposition
import Iut.Foundations.SourceTemperoidRestrictionComponentFamily
import Iut.Foundations.SourceConnectedFiniteEtaleConverse
import Iut.Foundations.SourceTemperedCoveringCategory
import Iut.Foundations.SourceTemperedGraphCoverRealization
import Iut.Foundations.SourceTemperedGeometricDomination
import Iut.Foundations.SourceTemperedActionCoverEquivalence
import Iut.Foundations.SourceFrobenioidBasePullbackLift
import Iut.Foundations.SourceFrobenioidUniversalProEvaluation
import Iut.Foundations.SourceModelFrobenioidPresentation
import Iut.Foundations.SourceModelRationalMonoidTransport
import Iut.Foundations.SourceModelFrobenioidRationalNaturality
import Iut.Foundations.SourceModelFrobenioidZeroEvaluation
import Iut.Foundations.SourceModelFrobenioidIntegralNaturality
import Iut.Foundations.SourceFiniteStageValuationDivisor
import Iut.Foundations.SourceFiniteStageDivisorTransition
import Iut.Foundations.SourceFiniteStageModelFrobenioid
import Iut.Foundations.SourceFiniteStageModelEvaluation
import Iut.Foundations.SourceDefinition52Sequential

/-!
  Trust-boundary audit for the imported semi-graph-of-anabelioids foundation.
  These declarations cover the pointwise finite-limit and supported finite-
  colimit constructions repaired for Lean/Mathlib 4.32.2, their preservation
  by vertex evaluation, and the resulting pre-Galois structure.
-/

#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.limitCone
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.limitConeIsLimit
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.evaluationMapLimitConeIsLimit
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.evaluationPreservesFiniteLimits
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.colimitCocone
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.colimitCoconeIsColimit
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.evaluationMapColimitCoconeIsColimit
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.evaluationPreservesFiniteCoproducts
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.evaluationPreservesFiniteGroupQuotientSmall
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.preGaloisCategory
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.complementFiberIsEmptyOfEpi
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.rootFiberFunctor
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.galoisCategory

#print axioms Iut.sourceInducedIdentityFiber_first_mem
#print axioms Iut.sourceInducedIdentityFiberToOriginal_original
#print axioms Iut.sourceInducedSliceFiberEvaluation_injective
#print axioms Iut.sourceContinuousAction_comp_apply
#print axioms Iut.sourceOpenCosetSliceEquivalence
#print axioms Iut.sourceSliceProductAdjDependentSection
#print axioms Iut.sourceInductionRestrictionAdjunction
#print axioms Iut.sourceOpenSubgroupFiniteEtaleFactorization

/-! Countable-base and finite-separator kernels ported from
`promachina/iut-lean@36ef280d`. -/

#print axioms Iut.SourceFiniteSheetSemiGraphCover.projection_vertexFiber_finite
#print axioms Iut.SourceFiniteSheetSemiGraphCover.projection_edgeFiber_finite
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.GaloisLevel.vertex_countable
#print axioms Iut.SourceSemiGraphOfAnabelioids.GluedObject.GaloisLevel.edge_countable
#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.deckGroup_countable
#print axioms Iut.SourceSemiGraphResidualSeparation.separationCover_vertex_countable
#print axioms Iut.SourceSemiGraphResidualSeparation.separationCover_edge_countable
#print axioms Iut.SourceSemiGraphResidualSeparation.separationTreeProjection_liftUniversalVertex

/-! Generic quotient and compatible-family inverse-limit kernel extracted from
`promachina/iut-lean@581e2b89`. -/

#print axioms Iut.SourceNestedNormalQuotientSystem.transition_mk
#print axioms Iut.SourceNestedNormalQuotientSystem.transition_surjective
#print axioms Iut.SourceNestedNormalQuotientSystem.transition_continuous
#print axioms Iut.SourceNestedNormalQuotientSystem.canonicalMap_continuous
#print axioms Iut.SourceNestedNormalQuotientSystem.canonicalMap_projection
#print axioms Iut.SourceNestedNormalQuotientSystem.canonicalMap_injective

/-! Connected finite coverings, kernel orbits, countable temperoids, and the
kernel-orbit/restriction adjunction ported from `promachina/iut-lean`. -/

#print axioms Iut.SourceConnectedCoveringCategory.categoryIsConnected
#print axioms Iut.SourceConnectedCoveringCategory.connected_iff_pretransitive
#print axioms Iut.EtaleFundamentalGroup.coverActionEquivalence

#print axioms Iut.SourceKernelOrbit.kernel_fixes
#print axioms Iut.SourceKernelOrbit.smul_mk
#print axioms Iut.SourceKernelOrbit.targetContinuous

#print axioms Iut.SourceConnectedTemperoid.connected_iff_nonempty_pretransitive
#print axioms Iut.SourceConnectedTemperoid.hom_surjective
#print axioms Iut.SourceConnectedTemperoid.categoryIsConnected
#print axioms Iut.SourceTemperoidAction.finiteInclusionFullyFaithful

#print axioms Iut.SourceTemperoidKernelQuotient.fiberTargetContinuous
#print axioms Iut.SourceTemperoidKernelQuotient.homEquiv
#print axioms Iut.SourceTemperoidKernelQuotient.adjunction
#print axioms Iut.SourceTemperoidKernelQuotient.restrictionFull
#print axioms Iut.SourceTemperoidKernelQuotient.connectedRestrictionFullyFaithful
#print axioms Iut.SourceTemperoidKernelQuotient.connectedAdjunction

#print axioms Iut.CategoryTheory.Functor.eval_section_surjective_of_bounded_lifts
#print axioms Iut.SourceCombinatorialUniversalCover.UniversalVertex.mapHom_bounded_surjective
#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.refinementIncidenceMap_fiber_finite
#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.refinementTreeMap_bounded_surjective
#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.refinementTreeMap_boundedFiber_finite
#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.deckTransition_surjective
#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.deckTransition_boundedFiber_finite
#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.deckTypeDiagram_eval_section_surjective
#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.rawDeckProjection_surjective
#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.literalTemperedPresentation_projection_surjective

#print axioms Iut.SourceTemperedGroupPresentation.projectionKernel_fixes_connectedAction
#print axioms Iut.SourceTemperedGroupPresentation.connectedActionLevelFactorization
#print axioms Iut.SourceCountableGroupDiagram.connectedActionLevelFactorization
#print axioms Iut.sourceTemperoidOrbitDecompositionIso
#print axioms Iut.SourceTemperedGroupPresentation.orbitLevelFactorization
#print axioms Iut.sourceTemperoidComponentFamilyActionIso
#print axioms Iut.sourceRestrictedComponentFamilyActionIso
#print axioms Iut.SourceFiniteEtaleFunctorFactorization.connectedObjectProfiniteInclusion_isOpenEmbedding
#print axioms Iut.SourceFiniteEtaleFunctorFactorization.connectedFiniteEtaleHom
#print axioms Iut.SourceFiniteEtaleFunctorFactorization.connectedFiniteEtaleHom_fundamentalGroupHom_eq

#print axioms Iut.SourceSemiGraphOfAnabelioids.CovObject.finiteInclusionFullyFaithful
#print axioms Iut.SourceSemiGraphOfAnabelioids.CovObject.coverProjection
#print axioms Iut.SourceSemiGraphOfAnabelioids.CovObject.coverSemiGraph_isCountable
#print axioms Iut.SourceSemiGraphOfAnabelioids.CovObject.IsTempered.exists_isSplitBy_of_isPointConnected
#print axioms Iut.SourceSemiGraphOfAnabelioids.CovObject.finiteCovObject_isTempered
#print axioms Iut.SourceSemiGraphOfAnabelioids.CovObject.finiteTemperedInclusionFullyFaithful
#print axioms Iut.SourceSemiGraphOfAnabelioids.CovObject.temperedCovInclusionFullyFaithful

#print axioms Iut.SourceSemiGraphOfAnabelioids.CovObject.finiteComponentComparison
#print axioms Iut.SourceSemiGraphOfAnabelioids.CovObject.finiteComponentComparison_vertex_injective
#print axioms Iut.SourceSemiGraphOfAnabelioids.CovObject.finiteComponentComparison_edge_injective
#print axioms Iut.SourceFiniteLevelUniversalCover.covObject_isTempered
#print axioms Iut.SourceFiniteLevelUniversalCover.coverComparison_isProper
#print axioms Iut.SourceFiniteLevelUniversalCover.coverComparison_isExcision
#print axioms Iut.SourceFiniteLevelUniversalCover.coverComparison_isGraphCovering
#print axioms Iut.SourceFiniteLevelUniversalCover.coverSemiGraph_isConnected

#print axioms Iut.SourceSemiGraphOfAnabelioids.CovObject.exists_galoisLevel_splitting
#print axioms Iut.SourceSemiGraphOfAnabelioids.CovObject.exists_galoisLevel_splitting_of_isPointConnected
#print axioms Iut.SourceSemiGraphOfAnabelioids.CovObject.galoisVertexStabilizerFixesTarget
#print axioms Iut.SourceSemiGraphOfAnabelioids.CovObject.galoisEdgeStabilizerFixesTarget
#print axioms Iut.SourceFiniteSheetSemiGraphCover.UniversalLift.projection_comp_hom
#print axioms Iut.SourceSemiGraphOfAnabelioids.CovObject.TargetSheetLift.branchRepresentativeCorrection_spec
#print axioms Iut.SourceSemiGraphOfAnabelioids.CovObject.TargetSheetLift.branchCarrierEquiv_edgePoint
#print axioms Iut.SourceSemiGraphOfAnabelioids.CovObject.GeometricDomination.branchNaturality
#print axioms Iut.SourceSemiGraphOfAnabelioids.CovObject.GeometricDomination.hom

/-! The finite-level and inverse-limit action-cover classification kernel
ported from `promachina/iut-lean@c7c06e23`. -/

#print axioms Iut.SourceTemperoidAssociatedQuotient.functorFaithful
#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.associatedTemperedFunctorFull
#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.associatedTemperedFunctorFaithful
#print axioms Iut.SourceSemiGraphOfAnabelioids.CovObject.AssociatedQuotient.connectedTemperedClassification
#print axioms Iut.SourceSemiGraphOfAnabelioids.CovObject.AssociatedQuotient.componentwiseTemperedClassification
#print axioms Iut.SourceSemiGraphOfAnabelioids.CovObject.AssociatedQuotient.componentwiseAssociatedQuotientClassification
#print axioms Iut.SourceSemiGraphOfAnabelioids.CovObject.AssociatedQuotient.globallyTemperedClassification

#print axioms Iut.DivisorialMonoidOn.gpPullback_comp
#print axioms Iut.PreFrobenioid.divisor_comp
#print axioms Iut.PreFrobenioid.frobeniusDegree_comp
#print axioms Iut.FrobenioidPresentation
#print axioms Iut.SplitFrobenioidEquivalence.refl
#print axioms Iut.SplitFrobenioidEquivalence.trans
#print axioms Iut.FrobenioidRationalMonoidTransport.isCoAngular_of_isotropicSource
#print axioms Iut.FrobenioidRationalMonoidTransport.isIsotropic_source_of_coAngular_linear
#print axioms Iut.FrobenioidRationalMonoidTransport.isIso_of_coAngular_isometric_preStep
#print axioms Iut.FrobenioidRationalMonoidTransport.rationalMonoidTransport
#print axioms Iut.FrobenioidIsotropicBase.projection_essSurj
#print axioms Iut.FrobenioidIsotropicBase.equivalence
#print axioms Iut.FrobenioidCoAngularBaseChange.isLinear_of_isIso
#print axioms Iut.FrobenioidCoAngularBaseChange.unitTransport_id
#print axioms Iut.FrobenioidCoAngularBaseChange.unitTransport_comp
#print axioms Iut.FrobenioidCoAngularBaseChange.commonCoAngularPreSteps
#print axioms Iut.FrobenioidCoAngularBaseChange.CommonCoAngularPreStepWitness.rationalMonoidEquiv_eq
#print axioms Iut.FrobenioidCoAngularBaseChange.baseIsoRationalMonoidEquiv_trans
#print axioms Iut.FrobenioidBasePullbackLift.isPullback_comp
#print axioms Iut.FrobenioidBasePullbackLift.baseArrowLift
#print axioms Iut.FrobenioidBasePullbackLift.BaseArrowLift.pullback_eq
#print axioms Iut.FrobenioidBasePullbackLift.baseArrowPullback_id
#print axioms Iut.FrobenioidBasePullbackLift.baseArrowPullback_comp
#print axioms Iut.FrobenioidBasePullbackLift.baseRationalMonoidFunctor
#print axioms Iut.FrobenioidUniversalProEvaluation.galoisAction
#print axioms Iut.FrobenioidUniversalProEvaluation.galoisAction_levelMap

#print axioms Iut.SourceModelFrobenioid.Carrier.frobenioidPresentation
#print axioms Iut.SourceModelFrobenioid.Carrier.rationalMonoidTransport
#print axioms Iut.SourceModelFrobenioid.Carrier.ColimitBirationalObject.frobenioidPresentation
#print axioms Iut.SourceModelFrobenioid.Carrier.ColimitBirationalObject.rationalFunctionNatIso_divisor_compatible
#print axioms Iut.SourceModelFrobenioid.Carrier.zeroObjectRationalFunctionEquiv
#print axioms Iut.SourceModelFrobenioid.Carrier.effectiveRationalFunctionPullback
#print axioms Iut.SourceModelFrobenioid.Carrier.zeroRationalFunctionNatIso
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageDivisorialMonoidOn
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageDivisorGrothendieckPullback_apply
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageModelInput
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageBaseTerminal
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageBase_isConnected
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageBase_arrow_epi
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageModelPreFrobenioidPresentation
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageDivisorGrothendieckEquivInt_intTo
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageModelEffectiveSubmonoid_eq
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageModelEffectiveRationalFunctionEquivIntegralMonoid
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageModelZeroObjectRationalFunctionEquivIntegralMonoid
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageModelEffectiveRationalFunctionEquivIntegralMonoid_natural
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageIntegralMonoidFunctor
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageModelEffectiveToIntegralNatIso
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageModelZeroObjectToIntegralNatIso
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageIntegralToIndCocone
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageIntegralFilteredColimitToInd
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageIntegralFilteredColimitToInd_cocone
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageIntegralFilteredColimitToInd_surjective
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageIntegralFilteredColimitToInd_injective
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageIntegralFilteredColimitEquivInd
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageModelZeroObjectFilteredFunctor
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageModelZeroObjectFilteredColimit
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageModelZeroObjectToIntegralCocone
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageModelZeroObjectFilteredColimitToIntegral
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageModelZeroObjectFilteredColimitToIntegral_cocone
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageIntegralToModelZeroObjectCocone
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageIntegralFilteredColimitToModelZeroObject
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageIntegralFilteredColimitToModelZeroObject_cocone
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageModelZeroObjectFilteredColimitIsoIntegral
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageModelZeroObjectFilteredColimitEquivInd
#print axioms _root_.Iut.SourceFinitePlaceReconstruction.stageModelZeroObjectFilteredColimitEquivSourceMLF
#print axioms Iut.SourceMLFIntegralMonoid.groupificationEquivAlgebraicClosureUnits
#print axioms Iut.SourceFinitePlaceReconstruction.indIntegralMonoidEquivSourceMLF
#print axioms Iut.SourceFinitePlaceReconstruction.indIntegralMonoidEquivSourceMLF_galois
#print axioms Iut.SourceFinitePlaceReconstruction.continuous_indGaloisMulAut
#print axioms Iut.SourceFinitePlaceReconstruction.continuous_indGaloisAction_comp_stageIntegralToInd
#print axioms Iut.SourceFinitePlaceReconstruction.integralIndSystemLimit
#print axioms Iut.SourceFinitePlaceReconstruction.integralIndSourceSequentialPresentation
#print axioms Iut.SourceFinitePlaceReconstruction.stageIsIntegral_closure_iff_valuation_le_one
#print axioms Iut.SourceFinitePlaceReconstruction.stageEffectiveRationalFunctionEquivIntegralMonoid

#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.refinementSplitsUniversalCover
#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.associatedTemperedRefinementIso
#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.geometricUniversalCoverFunctor
#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.actionCoverFunctor
#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.actionCoverFunctorFaithful
#print axioms Iut.SourceCombinatorialUniversalCover.SourceGaloisCombinatorialUniversalCover.actionCoverFunctorFull
