/- Copyright (c) 2026 LeanFormal contributors. All rights reserved. -/

import LeanFormal.IUT.IUTII.Kummer.KummerPolynomial

/-!
  Realizing the formal Kummer root in an algebraic extension.

  `KummerPolynomialData.Adjoined` is the quotient algebra generated by a
  formal root.  This file records the exact condition needed to map that
  quotient into a chosen field extension and constructs such a realization
  for the algebraic closure of each local p-adic field.  No irreducibility,
  degree calculation, Galois action, or vertical correspondence is inferred.
-/

namespace LeanFormal.IUT

structure AdjoinRootEmbedding {K : Type*} [Field K]
    (D : KummerPolynomialData K) (L : Type*) [Field L] [Algebra K L] where
  root : L
  root_pow_eq : root ^ D.exponent = algebraMap K L D.parameter

namespace AdjoinRootEmbedding

variable {K : Type*} [Field K]
variable (D : KummerPolynomialData K) (L : Type*) [Field L] [Algebra K L]

noncomputable def lift (R : AdjoinRootEmbedding D L) : D.Adjoined →ₐ[K] L :=
  AdjoinRoot.liftAlgHom D.polynomial (Algebra.ofId K L) R.root (by
    simp only [KummerPolynomialData.polynomial, Polynomial.eval₂_sub,
      Polynomial.eval₂_pow, Polynomial.eval₂_C, Polynomial.eval₂_X,
      sub_eq_zero]
    exact R.root_pow_eq)

@[simp] theorem lift_root (R : AdjoinRootEmbedding D L) :
    R.lift D L D.root = R.root := by
  exact AdjoinRoot.liftAlgHom_root D.polynomial (Algebra.ofId K L) R.root _

@[simp] theorem lift_of (R : AdjoinRootEmbedding D L) (x : K) :
    R.lift D L (AdjoinRoot.of D.polynomial x) = algebraMap K L x := by
  exact AdjoinRoot.liftAlgHom_of D.polynomial (Algebra.ofId K L) R.root _ x

theorem root_ne_zero (R : AdjoinRootEmbedding D L) : R.root ≠ 0 := by
  intro h
  have hp := R.root_pow_eq
  rw [h, zero_pow D.exponent_pos.ne'] at hp
  apply D.parameter_ne_zero
  apply (FaithfulSMul.algebraMap_injective K L)
  simpa using hp.symm

end AdjoinRootEmbedding

noncomputable def localKummerRootRealizationFor
    (p n : Nat) [Fact (Nat.Prime p)] (hn : 0 < n) :
    AdjoinRootEmbedding (localKummerPolynomialFor p n hn)
      (AlgebraicClosure ℚ_[p]) := by
  let D := localKummerPolynomialFor p n hn
  let P : Polynomial (AlgebraicClosure ℚ_[p]) :=
    Polynomial.X ^ n - Polynomial.C
      (algebraMap ℚ_[p] (AlgebraicClosure ℚ_[p]) (p : ℚ_[p]))
  have hdeg : P.degree ≠ 0 := by
    change (Polynomial.X ^ n - Polynomial.C
      (algebraMap ℚ_[p] (AlgebraicClosure ℚ_[p]) (p : ℚ_[p]))).degree ≠ 0
    rw [Polynomial.degree_X_pow_sub_C hn]
    exact_mod_cast hn.ne'
  let x := Classical.choose (IsAlgClosed.exists_root P hdeg)
  have hx : P.IsRoot x := Classical.choose_spec (IsAlgClosed.exists_root P hdeg)
  refine { root := x, root_pow_eq := ?_ }
  change x ^ n = algebraMap ℚ_[p] (AlgebraicClosure ℚ_[p]) (p : ℚ_[p])
  change Polynomial.eval x P = 0 at hx
  simpa only [P, Polynomial.eval_sub, Polynomial.eval_pow, Polynomial.eval_C,
    Polynomial.eval_X, sub_eq_zero] using hx

theorem localKummerRootRealizationFor_root_ne_zero
    (p n : Nat) [Fact (Nat.Prime p)] (hn : 0 < n) :
    (localKummerRootRealizationFor p n hn).root ≠ 0 := by
  exact AdjoinRootEmbedding.root_ne_zero
    (D := localKummerPolynomialFor p n hn)
    (L := AlgebraicClosure ℚ_[p])
    (localKummerRootRealizationFor p n hn)

end LeanFormal.IUT

namespace LeanFormal.IUT.Audit

def adjoinRootLocalEmbedding : Obligation :=
  { id := "IUT-II.adjoin-root-local-embedding"
    source := "IUT II, Kummer-polynomial preliminary layer"
    status := VerificationStatus.proved
    note :=
      "The formal AdjoinRoot root is mapped by Mathlib's liftAlgHom to a " ++
        "chosen root in the algebraic closure of ℚ_[p]. Root compatibility " ++
        "and non-vanishing are proved. This is strictly smaller than the " ++
        "paper's compatible rational-root/Galois-ratio Kummer realization; " ++
        "irreducibility, finite degree, Galois descent, and the vertical " ++
        "log-Kummer correspondence remain pending."
    dependsOn :=
      [ "IUT-II.kummer-polynomial-kernel", "IUT-I-II.local-prime-place-carrier" ] }

end LeanFormal.IUT.Audit
